### ISSUE TITLE
Refactor io extension

### ISSUE THREAD

**Issue by AlexDo1** [VForWaTer/metacatalog#284]
We want to refactor the (relatively complicated) `io` extension.  

**TODO:**
- [ ] `Entry.import_data()` is currently implemented directly into the `Entry` model, this method should only be available if the `io` extension is activated, we can use a wrapper function in the `io` extension for that.
- [ ] As an entirely new `io` extension is planned, we can give a FutureWarning when the `io` extension is used and deprecate it.
- [ ] Solve #256 along the way.

**Comment by mmaelicke** [comment]
These tasks are still valid. I guess it is fine to use `import_data` and `export_data` in the future as our interfaces and give a `FutureWarning`for all the rest
